# Generated by Django 6.0 on 2025-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_due_at_todo_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
